### ISSUE TITLE
Add Sparkgeo as a gold sponsor

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#100]
[Sparkgeo_Logo.zip](https://github.com/foss4g2018/foss4g2018/files/2196118/Sparkgeo_Logo.zip)

**Comment by msilikale05** [comment]
Okay, will do it tomorrow in the morning my time.

**Comment by timlinux** [comment]
![screen shot 2018-07-25 at 00 34 27](https://user-images.githubusercontent.com/178003/43169738-85e06c98-8fa2-11e8-85d0-3a22e36f8e40.png)
