### ISSUE TITLE
Add Sensefly as a Gold Sponsor

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#101]
![sensefly_logo](https://user-images.githubusercontent.com/280390/44114431-28407262-9fd9-11e8-8e4d-4bc980ecf5da.png)

**Comment by enockseth** [comment]
Already added as Silver Sponsor. Upgrade?

**Comment by Mloweedgar** [comment]
Sensefly has been Added  as a Gold Sponsor
