### ISSUE TITLE
We need to provide a promo graphic for OSGEO projects to add to their web sites

### ISSUE THREAD

**Issue by timlinux** [foss4g2018/foss4g2018#22]
https://drive.google.com/open?id=1GlYhhMcEW4wNhVi55lYLKDqRBW1wylPs

**Comment by enockseth** [comment]
Done. Added [here](https://www.osgeo.org/events/foss4g-2018/)

**Comment by timlinux** [comment]
![qgisorg_banner_foss4g2018_dar](https://user-images.githubusercontent.com/178003/35861022-f64889bc-0b4e-11e8-9267-5ead1339848c.png)

Here is one @anitagraser made for QGIS

**Comment by timlinux** [comment]
I will add it to the git repo too....

**Comment by anitagraser** [comment]
Note that this is not centered vertically, because we use it on qgis.org where there is an overlay on the bottom part of the graphics. 

Let me know if you need a version that is centered.

**Comment by enockseth** [comment]
Sure. Kindly share centered version too. Thanks.

**Comment by anitagraser** [comment]
![qgisorg_banner_foss4g2018_dar_centered](https://user-images.githubusercontent.com/590385/35943435-52e335f4-0c59-11e8-99a0-96f7f0777d80.png)
