### ISSUE TITLE
We need a FAQ page

### ISSUE THREAD

**Issue by timlinux** [foss4g2018/foss4g2018#28]
We should start an FAQ page to address common questions e.g.
Can I bring my spouse?
Will there be tours before / after
Travel arrangements
Malaria
Visas

**Comment by msilikale05** [comment]
1. I think for safari we should only consider people who will participate in the Conference, so if its spouse, or their brothers, then they will be allowed into the Tour package 
2. Also, in my opinion (i will confirm with studio 19) if the tour is for one day, it should be running parallel to the conference, everyday people should be able to register for the tours package. The registration should have a total number of people. If the required number of people is full there will be no more registration until the next day.
3. Travel arrangements are being made now with Studio 19.
4. Visa is the task for the Logistics to work out, its not yet being done yet.

**Comment by kettyadoch** [comment]
@ragnvald, does the FAQ page you mention refer to the 'Got Questions' page on the website? If yes, here's proposed additional content for the FAQ.

FAQ:
"Welcome to the FOSS4G Dar es Salaam FAQs. If you have a question that isn't answered below, email us. The FAQs will be updated regularly, so please check back occasionally for new information.

-What is the cost to register for the conference?
There are three ways to pay for the conference as listed on the Registration Page(https://2018.foss4g.or.tz/EventManagement/public/e/1/foss4g-2018-dar-es-salaam). Attendees are responsible for their lodging and travel expenses.

-Does everyone listed on a talk need to register for the conference?
Yes, everyone whose name is listed on the talk should register for the conference.

-I need to cancel my registration, what should I do?
There is a link in your registration confirmation email to cancel your registration. If you are unable to locate this email, please contact us at foss4gdar@gmail.com.


-I need to modify/cancel my room reservation, what should I do?
Please refer to the conference-specific 'Accommodation' section for detailed cancellation procedures.


-Are there any meals provided during the conference?
The conference provides lunch and coffees/teas during session breaks. There are no other meals provided.


-Will there be tours before / after the conference?
The conference committee is organizing two ways of sight seeing while in Dar es Salaam. 1. The 'Safari' which is offered for all people who will participate in the conference and 2. the 'Tour' which will accommodate spouses/relatives of conference participants. The tour will run parallel to the conference and will last one day,  everyday people should be able to register for the tours package. The registration should have a total number of people. If the required number of people is full there will be no more registration until the next day.  


-Can you please help with Tanzania visa information?
Please refer to the TZ Immigration Office(http://immigration.go.tz/index.php/en/services/visa-information) or speak to your consulate.The recommended visa for our conference delegates is the 'Single Entry Visa(Ordinary Visa)'. Should you require a conference invitation letter, please fill in this form: https://goo.gl/forms/ARybTSuqnHIpFzfl2


-Questions?
Feel free to contact us anytime at foss4gdar@gmail.com "

**Comment by ragnvald** [comment]
This is what I was thinking on. We need to cover as much as possible of
questions. One I had just now was:

Q: My institution does not allow me to make donations. Can I remove it?
A: You can uncheck the 'donate 5%' box.

Could you please add this one and the ones you mention above?


Ragnvald


2018-06-07 14:16 GMT+02:00 kettyadoch <notifications@github.com>:

**Comment by ragnvald** [comment]
I have added most questions. Did not add this one though because I am not sure the answer is correc: "Will there be tours before / after the conference?"

**Comment by brompo** [comment]
Hello Ragnvald

We are in discussion with Rickshaw on the tours, and we should be able to have a better answer on this soon

Will add this information once we have a clearer response on this.
