### ISSUE TITLE
Update the ticket booking page links

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#68]
The new ticketing system is now online: https://2018.foss4g.or.tz/EventManagement/public/e/1/foss4g-2018-dar-es-salaam. We need to update the links to this new ticketing site.

**Comment by brompo** [comment]
I do not have access to update the website, whoever has access please add the above link

**Comment by timlinux** [comment]
Current web site is updated now. New web site needs to be tweaked
