### ISSUE TITLE
Registration page should indicate what the cost savings is for early birds

### ISSUE THREAD

**Issue by timlinux** [foss4g2018/foss4g2018#70]
In https://2018.foss4g.or.tz/EventManagement/public/e/1/foss4g-2018-dar-es-salaam

Please update the text to add these bullets (indicated in bold):

Special early bird Ticket, together with

Early-Bird Gold Rate This ticket offers:- 

* Special early bird Ticket, together with
* 3 night accommodation at a 5-star hotel
* Entrance to the gala dinner, opening and closing parties! 
* **Save $200 on normal Gold rate**

$1,200.00 

Early-Bird Silver RateThis ticket offers:

* A special early bird ticket, together with
* 3 night accommodation at a 4-star hotel
* Entrance to the gala dinner, opening and closing parties!
* **Save $150 on normal Silver rate**
 $950.00 

Early-Bird Bronze Rate This ticket offers:- 
*  A special early bird ticket, together with
* 3 night accommodation at a 3-star hotel
* Entrance to the gala dinner, opening and closing parties!
* **Save $150 on normal Bronze rate**
 | $850.00

Early-Bird Ticket OnlyThis ticket offers:- 

* A special early bird ticket, together with
*  Entrance to the gala dinner, opening and closing parties!
* **Save $150 on normal rate**

**Comment by brompo** [comment]
Added the needed text
