### ISSUE TITLE
We need a news box on the front page

### ISSUE THREAD

**Issue by timlinux** [foss4g2018/foss4g2018#72]
We need a way to get important news front and center on our web site. For example the crowd sourced review of proposals should be advertised there. Can you please add a content block under the sponsors bar with a special post type that will show always the latest of that type in the block? Contact me if you need clarification.

**Comment by Mloweedgar** [comment]
we have added a section on the home page(https://2018.foss4g.org/) for latest announcement, please take a look and let us know if It is what you wanted.

**Comment by timlinux** [comment]
Thanks I see you have added the one under the countdown too so we can close this.
