### ISSUE TITLE
Add Immergis as a Silver Sponsor on the website

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#75]
![immergis_logo_sept 2016](https://user-images.githubusercontent.com/280390/40142993-34172ee8-5928-11e8-9339-c26960a98d9a.png)

Immergis is a silver sponsor - we need to link to: http://immergis.fr/en/ too!!

**Comment by Mloweedgar** [comment]
Iam working on  it. I also suggest using this plugin for other  new sponsors https://2018.foss4g.org/wp-admin/edit.php?post_type=tplogoshowcase. it is already configured in our wordpress site

**Comment by timlinux** [comment]
I think we can close this, they are added....
