### ISSUE TITLE
Add Spatial Networks as a Bronze Sponsor

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#95]
![2017-sni-logo-web](https://user-images.githubusercontent.com/280390/41499959-85246f16-7157-11e8-9e06-2758658c9db0.png)

**Comment by markiliffe** [comment]
I've added it - but can we fix it so it's in the 3rd column? Cheers!!

**Comment by timlinux** [comment]
Done @markiliffe 

FYI if you are doing it youself, just edit the sponsors page in plain mode and copy one of the above lines e.g.:

```

<div class="partner col-md-4 col-sm-3 col-xs-4">[logo_showcase id="751"]</div>
```

It needs the class="blah blah" stuff to wrap properly.

**Comment by timlinux** [comment]
![screen shot 2018-06-18 at 14 55 26](https://user-images.githubusercontent.com/178003/41537078-ac4a57c0-7307-11e8-8b1d-101c44a9f2a2.png)
