### ISSUE TITLE
Add Development Seed as a Gold Sponsor

### ISSUE THREAD

**Issue by markiliffe** [foss4g2018/foss4g2018#98]
![devseed-logo-full](https://user-images.githubusercontent.com/280390/42140903-ce7786ea-7d72-11e8-8262-5b17c91dcb19.png)
Add Development Seed as a Gold Sponsor!

**Comment by mkumbobeaty** [comment]
@markiliffe can you share the link to the sponsor's website. The logo image has been added to the website already.

**Comment by ldgillen** [comment]
@mkumbobeaty link to our website: https://developmentseed.org/

Thanks, both!

**Comment by timlinux** [comment]
Done here:

<img width="1138" alt="screen shot 2018-07-05 at 11 32 05" src="https://user-images.githubusercontent.com/178003/42315204-24027d64-8047-11e8-8e23-0a91cca8f4bd.png">
